---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-demos-roadtok8s-com-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: js-demos-roadtok8s-com-deployment
  template:
    metadata:
      labels:
        app: js-demos-roadtok8s-com-deployment
    spec:
      containers:
        - name: js-demos-roadtok8s-com-container
          image: roadtokubernetes/js.demo.roadtok8s.com:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3001"
          ports:
            - containerPort: 3001

