apiVersion: v1
kind: Service
metadata:
  name: js-demos-roadtok8s-com-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
  selector:
    app: js-demos-roadtok8s-com-deployment


