apiVersion: v1
kind: Service
metadata:
  name: service.js.demos.roadtok8s.com
  namespace: default 
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
  selector:
    app: deployment.js.demos.roadtok8s.com


